### ISSUE TITLE
Re-consider how we use issues

### ISSUE THREAD

**Issue by patcon** [pol-is/polis-issues#101]
Some fact/feelings/ideas:

:mag: GitHub now [allows organization-wide project kanban boards](https://blog.github.com/2016-10-27-introducing-projects-for-organizations/).
:mag: Polis [isn't currently using any](https://github.com/orgs/pol-is/projects).
:mag: GitHub issues are disabled on: `polisClientAdmin`, `polisServer`, `polisMath`
:mag: GitHub issues are enabled on: `polisClientParticipation`
:heart: I feel that conversations initiating in issues (before code appears) is a positive pattern.
:heart: I feel that disabling repo issues discourages the most obvious and intuitive path to communicating around code (that many users develop github muscle memory around).
:heart: I feel that disabling issues on repos is an anti-pattern for canonical (non-forked) repos.
:heart: I feel curious whether Trello is the better tool for non-code-specific tasks.
:heart: I often feel that issues specific to a component's code belong in that code's repo.

**Comment by metasoarous** [comment]
I'm open to allowing issues on individual projects. I think it's nice to have a central `issues` repo as we do presently though, as it provides a place for issues when you aren't sure what the issue is, and as you mention, for non-code specific tasks.

I'm actually a fan of ZenHub for kanban. It allows for looking at multiple repos together. I haven't tried GH's Projects yet. Seems potentially a bit less intuitive/powerful, but I'd be willing to give it a go.

I'm not keen on changing anything here immediately given other priorities, but we can continue to have the discussion.

**Comment by patcon** [comment]
This moved forward in pol-is/polis-issues#128 :)
