### ISSUE TITLE
Improvement for polisClientParticipation configuration

### ISSUE THREAD

**Issue by crkrenn** [pol-is/polis-issues#110]
The repos for both polisClientAdmin and polisClientParticipation do not have a default polis.config.js, but requires the user to "cp polis.config.template.js polis.config.js" and edit polis.config.js as needed. But, polisClientAdmin and polisClientParticipation have a default webpack.config.js that is set up for a production environment. 

I suggest to "git mv webpack.config.js webpack.config.prod.js", "ln -sf webpack.config.js webpack.config.prod.js" and to update the README.md files appropriately. I can write two PR's for this. 

parallels@ubuntu:~/polis_master/polis_source$ ls -1  */*config*
polisClientAdmin/polis.config.template.js
polisClientAdmin/webpack.config.dev.js
polisClientAdmin/webpack.config.js
polisClientAdmin/webpack.config.unminified.js

polisClientParticipation/polis.config.template.js
polisClientParticipation/webpack.config.dev.js
polisClientParticipation/webpack.config.js
polisClientParticipation/webpack.config.unminified.js

**Comment by metasoarous** [comment]
Thinking about this a bit, I think the reason things were set up this way is so that `polis.config.js` can be in the `.gitignore` to avoid committing credentials. The scenario is a bit different for the `webpack.config.js` files, as these don't contain any sensitive information.

As it stands it's assumed that you're going to need to enter in these credentials one way or the other anyway, so it may not be such a big deal to assume that users just have to copy these over, as long as this is explained well in the documentation. If there's a way you can think to make this process clearer or easier though, I'm all ears.

**Comment by patcon** [comment]
My understanding is that this isn't an issue anymore, so closing for now, but pls do request re-opening if I'm in the wrong!
