### ISSUE TITLE
A working branch for running pol-is development with docker-compose

### ISSUE THREAD

**Issue by crkrenn** [pol-is/polis-issues#125]
@david-nadaraia and I have been working on dockerizing pol-is. 

**And, we have a working branch!**

We will work on some pull requests soon, but in the meantime, you can paste the following into a shell. (This has been tested on Ubuntu and OSX, but has not yet been tested on Windows.)

    mkdir polis_docker_local
    cd polis_docker_local
    git clone https://github.com/crkrenn/polis-deploy
    cd polis-deploy
    git checkout docker_dgps_C
    cd docker_compose
    ./install
    ./start # using bash (without sudo for docker-compose e.g. osx)
    ./start sudo # using bash (with sudo for docker-compose e.g. ubuntu)
    echo "done!"
Connect to http://localhost:5000

**Comment by colinmegill** [comment]
Amazing! Thanks @crkrenn && @david-nadaraia!

**Comment by colinmegill** [comment]
There are a lot of people who will be excited to see this progress.

**Comment by metasoarous** [comment]
Hi @crkrenn!

Thanks so much for pushing forward on this front!

If you put up a PR, I'd be more than happy to merge this in.

Thanks again!

**Comment by crkrenn** [comment]
I did submit pull requests, but they change behavior of the current Dockerfiles.

I think they can wait a bit.

Though, they might be appropriate for a “dev” branch;)

C.


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On March 31, 2020 at 4:34:27 PM PDT, Christopher Small <notifications@github.com> wrote:

Hi @crkrenn<https://github.com/crkrenn>!

Thanks so much for pushing forward on this front!

If you put up a PR, I'd be more than happy to merge this in.

Thanks again!

**Comment by patcon** [comment]
My in-progress docker exploration here: https://github.com/pol-is-trial-balloon/polisCode/compare/monorepo...patcon:docker-dev

- tried proxying all requests through nginx at first, but realized it would be quite a divergence from the official approach of polisServer proxying through to fileserver.js, so was then trying to get a minimal variation of the official way working
- currently spins up, but only clientAdmin works (serving through ngxinx). clientParticipation doesn't work due to the way frontend code can't be served directly, but needs to proxy through polisServer in order to have preloaded data replaced into the request
- using multi-stage docker build for `fileServer/` and pre-compilation of frontend UI.
  - working on getting `*.headersJson` generating for local copy deploy (scp/s3 deploy doesn't make sense for local deploy to directory that's best for docker setup)

**Comment by patcon** [comment]
Ah hey, I think we can close this 🎉
