### ISSUE TITLE
Don't apply vote for seed comments submitted by admin

### ISSUE THREAD

**Issue by patcon** [pol-is/polis-issues#34]
There was a previous issue for making seed comments anonymous, as they used to be attributed to the admin account.

It seems that seed comments are now anonymous, but that creation of the comment attributes an AGREE vote from the admin account.

To reproduce, create a new conversation, and add comments through the "Configure" page. Now, when going to the public url, instead of being able to vote on the new seed comments, the user sees the subscription card, as if they had already voted.

This seems non-ideal, as an admin participant can't submit comments for which they disagree, and must instead use convoluted negation in order to seed and participate properly.

**Comment by metasoarous** [comment]
I fully agree. We've left this as is for a while because it complicates the math polling; The math poller works by polling for votes, and if a comment entered the system without a vote, it would throw a bunch of implicit indexing out of whack. This should definitely be solved though, because it's a terrible limitation.

Talking with @mbjorkegren, the thing to do is probably look when we have a new comment id on a vote to see whether it's either already been seen or is the successor of some already seen id. If it's not, then we can assume we have a seeded comment, and insert nil rows in the vote matrix corresponding to the unseen ids. This shouldn't effect the math, as the zero column will effectively be factored out of the PCA results with 0 variance.

**Comment by patcon** [comment]
If we wish to kick the can a little further down the road (no judgement!), then allowing seeds to be submitted as DISAGREE, or even PASS, would also address the root concern. Perhaps via less prominent buttons. After all, this minor issue will only ever affect moderators :)

Then again, it will prob be pretty important to near-future gov moderators that the first vote not be their own (in the interest of objective consultations).

**Comment by metasoarous** [comment]
Was just looking through outstanding issues, and realized that we ended up doing most of the math work for this recently in sorting out the the handling of `is_meta` comment attributes. So I _think_ that we can now just remove the default, if this hasn't been done already. @mbjorkegren did you do that when we finished up the `is_meta` and `mod` work?

**Comment by patcon** [comment]
Ah, just confirmed on public prod instance. Steps:

1. Create a new conversation.
2. Add a seed comment.
3. Open to participation view in a new tab, still logged in.

Since the submitted comment was shown on a card with the ability to vote, I assume that an initial vote was not applied 🎉 

Thanks all! Closing!
